sentiment analysis dataset Fastfood_Opinion.csv ด้วยเทคนิค Naïve Bayes และ Logistic Regression

In [1]:
!pip install pythainlp

In [2]:
!wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1K0VgdwYagNidu5k_y5pnSrGrGIOBPsyS' -O fastfood_opinion.csv

zsh:1: command not found: wget


# Logistic Regression

In [3]:
import pandas as pd
import numpy as np
from pythainlp.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Step 1: Load and preprocess the data
data = pd.read_csv('fastfood_opinion.csv')  # Replace 'your_dataset.csv' with the path to your dataset
X = data['message'].astype(str)  # Text data in the 'message' column
y = data['class']  # Labels in the 'class' column


# Step 2: Create bag-of-words representation
# Preprocess the data Before training the model, you need to preprocess the Thai text data to convert it into tokenized
# and numerical features. We'll use scikit-learn's CountVectorizer to transform the text data into bag-of-word features (bow).

# Tokenize Thai text
X_tokenized = X.apply(word_tokenize, keep_whitespace=False)

# Bag of Words
vectorizer = CountVectorizer(analyzer=lambda x: x)  # Use the list of tokens as the analyzer
X_bow = vectorizer.fit_transform(X_tokenized)
print("X_bow ", X_bow.shape) # (documents, vocab)

vocab_bow = np.array(vectorizer.get_feature_names_out())
print(vocab_bow.shape)
print(vocab_bow[250:270])


# Binary Term
binary_vectorizer= CountVectorizer(analyzer=lambda x: x, binary=True)  # binary=True for binary term frequency
X_binary = binary_vectorizer.fit_transform(X_tokenized)
print("X_binary ", X_bow.shape) # (documents, vocab)

vocab_binary = np.array(binary_vectorizer.get_feature_names_out())
print(vocab_binary.shape)
print(vocab_binary[250:270])

# Bigram term
bigram_vectorizer = CountVectorizer(analyzer=lambda x: x, ngram_range=(1, 2))
X_bigram = bigram_vectorizer.fit_transform(X_tokenized)
print("X_bigram ", X_bigram.shape) # (documents, vocab)

vocab_bigram = np.array(bigram_vectorizer.get_feature_names_out())
print(vocab_bigram.shape)
print(vocab_bigram[250:270])

X_bow  (642, 3542)
(3542,)
['M' 'MBK' 'Mall' 'Management' 'Market' 'McDonalds' 'Mega' 'Moouse'
 'Mortor' 'Motorway' 'Mushroom' 'Nugget' 'Operation' 'Order' 'POS'
 'Paradise' 'Park' 'Piroj' 'Pizza' 'Place']
X_binary  (642, 3542)
(3542,)
['M' 'MBK' 'Mall' 'Management' 'Market' 'McDonalds' 'Mega' 'Moouse'
 'Mortor' 'Motorway' 'Mushroom' 'Nugget' 'Operation' 'Order' 'POS'
 'Paradise' 'Park' 'Piroj' 'Pizza' 'Place']
X_bigram  (642, 3542)
(3542,)
['M' 'MBK' 'Mall' 'Management' 'Market' 'McDonalds' 'Mega' 'Moouse'
 'Mortor' 'Motorway' 'Mushroom' 'Nugget' 'Operation' 'Order' 'POS'
 'Paradise' 'Park' 'Piroj' 'Pizza' 'Place']


/opt/anaconda3/lib/python3.12/site-packages/sklearn/feature_extraction/text.py:541: UserWarning: The parameter 'ngram_range' will not be used since 'analyzer' is callable'
  warnings.warn(


In [4]:
# Bag of Words
print(X_tokenized[2])
print("X_bow")
print(X_bow[2])

print(vocab_bow[3477])
print(vocab_bow[1341])
print(vocab_bow[2352])

['Burger', 'King', 'สาขา', 'The', 'Bright', 'พระราม', '2', 'บริการ', 'ห่วย', 'มาก', 'ถึง', 'มาก', 'ที่สุด', 'วันนี้', 'ไป', 'ทาน', 'กับ', 'ลูก', '3', 'คน', 'พนักงาน', 'รับ', 'ออเดอร์', 'มัวแต่', 'คุย', 'เล่น', 'กัน', 'ยืน', 'กัน', 'หลาย', 'คน', 'แต่', 'เปิด', 'เคา', 'เตอร์', 'เดียว', 'กว่า', 'จะ', 'สั่ง', 'ได้', 'นาน', 'มาก', 'พอ', 'สั่ง', 'แล้ว', 'เฟรนฟ', 'ราย', 'หมด', 'พอดี', 'พนักงาน', 'บอ', 'กว่า', 'เดี๋ยว', 'เอา', 'ไป', 'ให้', 'ที่', 'โต๊ะ', 'ก็', 'ไม่เป็นไร', 'ก็', 'ไป', 'นั่ง', 'รอ', 'ก็', 'นั่ง', 'ป้อน', 'แฮมเบอร์เกอร์', 'ลูก', 'ๆ', 'ไป', 'ซัก', 'พักใหญ่', 'เฟรนฟ', 'ราย', 'ก็', 'ยัง', 'ไม่', 'มา', 'แต่', 'เห็น', 'โต๊ะ', 'อื่น', 'ที่มา', 'หลัง', 'เรา', 'ได้', 'แล้ว', 'ก็', 'ลุก', 'ไป', 'ตาม', 'กับ', 'ผู้จัดการ', '(', 'แต่งตัว', 'ไม่', 'เหมือน', 'คนอื่น', ')', 'ตาม', 'ครั้ง', 'ที่', '1', 'ก็', 'ได้รับ', 'คำตอบ', 'เหมือนเดิม', 'ไป', 'นั่ง', 'รอ', 'ที่', 'โต๊ะ', 'เดี๋ยว', 'ไป', 'เส', 'ริ', 'ฟ', 'ให้', 'จน', 'ป้อน', 'เด็ก', 'จน', 'หมด', 'ใช้เวลา', 'ประมาณ', '30', 'นาที', 'ก็', 'เดิน

In [5]:

# Binary Term
print("X_binary")
print(X_binary[2])

print(vocab_binary[3477])
print(vocab_binary[1341])
print(vocab_binary[2352])


X_binary
  (0, 3477)	1
  (0, 1341)	1
  (0, 2352)	1
  (0, 3418)	1
  (0, 2149)	1
  (0, 123)	1
  (0, 489)	1
  (0, 1237)	1
  (0, 857)	1
  (0, 1309)	1
  (0, 2906)	1
  (0, 1876)	1
  (0, 1524)	1
  (0, 682)	1
  (0, 576)	1
  (0, 3203)	1
  (0, 1877)	1
  (0, 701)	1
  (0, 846)	1
  (0, 3459)	1
  (0, 559)	1
  (0, 3487)	1
  (0, 3139)	1
  (0, 2242)	1
  (0, 679)	1
  :	:
  (0, 491)	1
  (0, 2631)	1
  (0, 1220)	1
  (0, 2721)	1
  (0, 2882)	1
  (0, 3309)	1
  (0, 3468)	1
  (0, 13)	1
  (0, 1783)	1
  (0, 2448)	1
  (0, 1532)	1
  (0, 3490)	1
  (0, 2177)	1
  (0, 2864)	1
  (0, 3375)	1
  (0, 3406)	1
  (0, 1873)	1
  (0, 1522)	1
  (0, 2879)	1
  (0, 918)	1
  (0, 2391)	1
  (0, 2751)	1
  (0, 1960)	1
  (0, 1556)	1
  (0, 818)	1
ไป
ที่
สาขา


In [6]:
# Bigram term
print("X_bigram")
print(X_bigram[2])

print(vocab_bigram[3477])
print(vocab_bigram[1341])
print(vocab_bigram[2352])

X_bigram
  (0, 3477)	12
  (0, 1341)	8
  (0, 2352)	1
  (0, 3418)	1
  (0, 2149)	1
  (0, 123)	3
  (0, 489)	1
  (0, 1237)	1
  (0, 857)	2
  (0, 1309)	1
  (0, 2906)	1
  (0, 1876)	5
  (0, 1524)	1
  (0, 682)	2
  (0, 576)	9
  (0, 3203)	3
  (0, 1877)	5
  (0, 701)	2
  (0, 846)	5
  (0, 3459)	2
  (0, 559)	2
  (0, 3487)	5
  (0, 3139)	2
  (0, 2242)	1
  (0, 679)	1
  :	:
  (0, 491)	1
  (0, 2631)	1
  (0, 1220)	1
  (0, 2721)	1
  (0, 2882)	1
  (0, 3309)	1
  (0, 3468)	2
  (0, 13)	2
  (0, 1783)	2
  (0, 2448)	1
  (0, 1532)	1
  (0, 3490)	1
  (0, 2177)	1
  (0, 2864)	2
  (0, 3375)	1
  (0, 3406)	1
  (0, 1873)	1
  (0, 1522)	1
  (0, 2879)	1
  (0, 918)	1
  (0, 2391)	1
  (0, 2751)	1
  (0, 1960)	1
  (0, 1556)	1
  (0, 818)	1
ไป
ที่
สาขา


In [7]:
# Bow
# Step 3: Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

# Step 4: Train the binomial logistic regression
logreg_classifier = LogisticRegression()
logreg_classifier.fit(X_train, y_train)

# Step 5: Evaluate the model
y_pred = logreg_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Bow")
print("Accuracy:", accuracy)

Bow
Accuracy: 0.8837209302325582


In [8]:
from sklearn.metrics import classification_report, confusion_matrix

# Print classification report (precision, recall, F1-score, support)
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.85      0.89        74
           1       0.82      0.93      0.87        55

    accuracy                           0.88       129
   macro avg       0.88      0.89      0.88       129
weighted avg       0.89      0.88      0.88       129

Confusion Matrix:
[[63 11]
 [ 4 51]]


In [9]:
# Binary
# Step 3: Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_binary, y, test_size=0.2, random_state=42)

# Step 4: Train the binomial logistic regression
logreg_classifier = LogisticRegression()
logreg_classifier.fit(X_train, y_train)

# Step 5: Evaluate the model
y_pred = logreg_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Binary")
print("Accuracy:", accuracy)

Binary
Accuracy: 0.9147286821705426


In [10]:
from sklearn.metrics import classification_report, confusion_matrix

# Print classification report (precision, recall, F1-score, support)
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.89      0.92        74
           1       0.87      0.95      0.90        55

    accuracy                           0.91       129
   macro avg       0.91      0.92      0.91       129
weighted avg       0.92      0.91      0.92       129

Confusion Matrix:
[[66  8]
 [ 3 52]]


In [11]:
# Bigram
# Step 3: Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_bigram, y, test_size=0.2, random_state=42)

# Step 4: Train the binomial logistic regression
logreg_classifier = LogisticRegression()
logreg_classifier.fit(X_train, y_train)

# Step 5: Evaluate the model
y_pred = logreg_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Bigram")
print("Accuracy:", accuracy)

Bigram
Accuracy: 0.8837209302325582


In [12]:
from sklearn.metrics import classification_report, confusion_matrix

# Print classification report (precision, recall, F1-score, support)
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.85      0.89        74
           1       0.82      0.93      0.87        55

    accuracy                           0.88       129
   macro avg       0.88      0.89      0.88       129
weighted avg       0.89      0.88      0.88       129

Confusion Matrix:
[[63 11]
 [ 4 51]]


In [13]:
# Predict New Data: Example 1

new_text = "กินที่ร้านดีกว่าครับ ลองสั่งมากินที่บ้านครั้งแรก ไม่มีความร้อนเลย ความอร่อยยังดีเหมือนเดิม"
new_text = pd.Series(new_text)
new_text_tokenized = new_text.apply(word_tokenize, keep_whitespace=False)
new_text_bow = vectorizer.transform(new_text_tokenized)

predicted_class = logreg_classifier.predict(new_text_bow)
print("Predicted Class: ", predicted_class[0])

print(new_text_tokenized)
print(new_text_bow)

Predicted Class:  1
0    [กินที่, ร้าน, ดีกว่า, ครับ, ลอง, สั่ง, มา, กิ...
dtype: object
  (0, 562)	2
  (0, 698)	1
  (0, 705)	1
  (0, 722)	1
  (0, 739)	1
  (0, 1045)	1
  (0, 1046)	1
  (0, 1584)	1
  (0, 1876)	1
  (0, 1899)	1
  (0, 1951)	1
  (0, 2125)	1
  (0, 2144)	1
  (0, 2343)	1
  (0, 2585)	1
  (0, 3027)	1
  (0, 3107)	1
  (0, 3487)	1


In [14]:
# Predict New Data: Example 2


new_text = ["พนักงานช้ามาก ขนาดเช้าคนไม่เยอะ ก็หน้าบึ้งละ ไม่สมเป็น fast food ระดับโลก น่าจะสนใจคัดเลือกพนักงานได่ดีกว่านี้"]
new_text = pd.Series(new_text)
new_text_tokenized = new_text.apply(word_tokenize, keep_whitespace=False)
new_text_bow = vectorizer.transform(new_text_tokenized)

predicted_class = logreg_classifier.predict(new_text_bow)
print("Predicted Class: ", predicted_class[0])

print(new_text_tokenized)
print(new_text_bow)


Predicted Class:  0
0    [พนักงาน, ช้า, มาก, ขนาด, เช้า, คน, ไม่, เยอะ,...
dtype: object
  (0, 576)	1
  (0, 597)	1
  (0, 682)	1
  (0, 976)	1
  (0, 1046)	1
  (0, 1464)	1
  (0, 1480)	1
  (0, 1723)	2
  (0, 1877)	1
  (0, 2149)	1
  (0, 2281)	1
  (0, 2289)	1
  (0, 2459)	1
  (0, 2781)	1
  (0, 2911)	1
  (0, 2989)	1
  (0, 3487)	2


# Naive Bays

In [15]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

from pythainlp.tokenize import word_tokenize

# Step 1: Load and preprocess the data
data = pd.read_csv('fastfood_opinion.csv')  # Replace 'your_dataset.csv' with the path to your dataset
X = data['message'].astype(str)  # Text data in the 'message' column
y = data['class']  # Labels in the 'class' column

# Tokenize Thai text
X_tokenized = X.apply(word_tokenize, keep_whitespace=False)

# Step 2: Create bag-of-words representation
vectorizer2 = CountVectorizer(analyzer=lambda x: x)  # Use the list of tokens as the analyzer
X_bow = vectorizer2.fit_transform(X_tokenized)
print(X_bow.shape) # (documents, vocab)

# Step 3: Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

# Step 4: Train the binomial Naive Bayes classifier
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)

# Step 5: Evaluate the model
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


(642, 3542)
Accuracy: 0.8992248062015504


In [16]:
new_text = ["กินที่ร้านดีกว่าครับ ลองสั่งมากินที่บ้านครั้งแรก ไม่มีความร้อนเลย ความอร่อยยังดีเหมือนเดิม", "พนักงานช้ามาก ขนาดเช้าคนไม่เยอะ ก็หน้าบึ้งละ ไม่สมเป็น fast food ระดับโลก น่าจะสนใจคัดเลือกพนักงานได่ดีกว่านี้"]
new_text = pd.Series(new_text)
new_text_tokenized = new_text.apply(word_tokenize, keep_whitespace=False)
new_text_bow = vectorizer2.transform(new_text_tokenized)

predicted_class = nb_classifier.predict(new_text_bow)
print("Predicted Class:", predicted_class)

print(new_text_tokenized)
print(new_text_bow)

Predicted Class: [0 0]
0    [กินที่, ร้าน, ดีกว่า, ครับ, ลอง, สั่ง, มา, กิ...
1    [พนักงาน, ช้า, มาก, ขนาด, เช้า, คน, ไม่, เยอะ,...
dtype: object
  (0, 562)	2
  (0, 698)	1
  (0, 705)	1
  (0, 722)	1
  (0, 739)	1
  (0, 1045)	1
  (0, 1046)	1
  (0, 1584)	1
  (0, 1876)	1
  (0, 1899)	1
  (0, 1951)	1
  (0, 2125)	1
  (0, 2144)	1
  (0, 2343)	1
  (0, 2585)	1
  (0, 3027)	1
  (0, 3107)	1
  (0, 3487)	1
  (1, 576)	1
  (1, 597)	1
  (1, 682)	1
  (1, 976)	1
  (1, 1046)	1
  (1, 1464)	1
  (1, 1480)	1
  (1, 1723)	2
  (1, 1877)	1
  (1, 2149)	1
  (1, 2281)	1
  (1, 2289)	1
  (1, 2459)	1
  (1, 2781)	1
  (1, 2911)	1
  (1, 2989)	1
  (1, 3487)	2
